Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import pandas as pd
from scipy.stats import binom
import matplotlib
import matplotlib.pyplot as plt   
import metakernel
from IPython.display import display, Markdown, clear_output
import ipywidgets as widgets    
from ipywidgets import interact, interactive, fixed, interact_manual
import ipynb
from ipynb.fs.full.Problem02back import *

n_slider = widgets.IntSlider(min=1, max=5000, step=1, value=100)
m_slider = widgets.IntSlider(min=1, max=99, step=1, value=9)
x_slider = widgets.IntSlider(min=1, max=n_slider.value, step=1, value=40)
Î¹_slider = widgets.IntSlider(min=1, max=m_slider.value - 1, step=0, value=3)

n_slider.observe(update_x_range, 'value')
m_slider.observe(update_Î¹_range, 'value')

interact(bayes_binomials_uniform_prior, n=n_slider, m=m_slider, x=x_slider, Î¹=Î¹_slider)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 10[0m
[1;32m      8[0m [38;5;28;01mimport[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mas[39;00m [38;5;21;01mwidgets[39;00m    
[1;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mimport[39;00m interact, interactive, fixed, interact_manual
[0;32m---> 10[0m [38;5;28;01mimport[39;00m [38;5;21;01mipynb[39;00m
[1;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipynb[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfs[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfull[39;00m[38;5;21;01m.[39;00m[38;5;21;01mProblem02back[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     13[0m n_slider [38;5;241m=[39m widgets[38;5;241m.[39mIntSlider([38;5;28mmin[39m[38;5;241m=[39m[38;5;241m1[39m, [38;5;28mmax[39m[38;5;241m=[39m[38;5;241m5000[39m, step[38;5;241m=[39m[38;5;241m1[39m, value[38;5;241m=[39m[38;5;241m100[39m)

[0;31mModuleNotFoundError[0m: No module named 'ipynb'

